services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: reveste
      POSTGRES_USER: reveste
      POSTGRES_PASSWORD: reveste
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reveste -d reveste"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dados_postgres:/var/lib/postgresql/data
      - ./db/migrations/001_modelo_inicial.up.sql:/docker-entrypoint-initdb.d/001_modelo_inicial.sql:ro
      - ./db/migrations/002_anuncio_unico_por_item.up.sql:/docker-entrypoint-initdb.d/002_anuncio_unico_por_item.sql:ro
      - ./db/migrations/003_categorias_anuncio.up.sql:/docker-entrypoint-initdb.d/003_categorias_anuncio.sql:ro

volumes:
  dados_postgres:
